### ISSUE TITLE
404 error when following OSI submodule link

### ISSUE THREAD

**Issue by PhRosenberger** [openMSL/reflection_based_lidar_object_model#17]
**Describe the bug:**
When I click on the OSI submodule at https://github.com/openMSL/sl-1-2-reflection-based-lidar-object-model/tree/main/lib, I get an 404 error. Should we probably change the submodule to the last commit of the SETLevel OSI main branch under https://gitlab.setlevel.de/open/osi?

**Comment by ClemensLinnhoff** [comment]
This is odd. It already points to the last commit of https://gitlab.setlevel.de/open/osi. At least the commit ID and the url in .gitmodules match. But I will check this on a branch.

**Comment by ClemensLinnhoff** [comment]
I just checked. When I locally pull the main branch in lib/open-simulation-interface, nothing happens. So it is already the current commit of the main branch of SETLevel OSI. I don't know why the link from the GitHub page does not work. But it also doesn't work for eigen (pointing to a GitLab) repository. So probably GitHub just does not link to GitLab.

So can we close this issue @PhRosenberger ?

**Comment by PhRosenberger** [comment]
Oh ok, so it's more about GitHub not liking GitLab..
